// Auto-generated ROM registry
// Maps ROM filenames to stable auto-incremented IDs

const romRegistry: Record<string, number> = {
  "10-Yard Fight (USA, Europe).nes": 1,
  "1942 (Japan, USA).nes": 2,
  "1943 - The Battle of Midway (USA).nes": 3,
  "3-D WorldRunner (USA).nes": 4,
  "720 Degrees (USA).nes": 5,
  "8 Eyes (USA).nes": 6,
  "Abadox - The Deadly Inner War (USA).nes": 7,
  "Action 52 (USA) (Rev A) (Unl).nes": 8,
  "Addams Family, The (USA).nes": 9,
  "Addams Family, The - Pugsley's Scavenger Hunt (USA).nes": 10,
  "Advanced Dungeons & Dragons - DragonStrike (USA).nes": 11,
  "Advanced Dungeons & Dragons - Dragons of Flame (Japan) (Translated En).nes": 12,
  "Advanced Dungeons & Dragons - Heroes of the Lance (USA).nes": 13,
  "Advanced Dungeons & Dragons - Hillsfar (USA).nes": 14,
  "Advanced Dungeons & Dragons - Pool of Radiance (USA).nes": 15,
  "Adventure Island (USA).nes": 16,
  "Adventure Island II (USA).nes": 17,
  "Adventure Island III (USA).nes": 18,
  "Adventures in the Magic Kingdom (USA).nes": 19,
  "Adventures of Bayou Billy, The (USA).nes": 20,
  "Adventures of Dino Riki (USA).nes": 21,
  "Adventures of Gilligan's Island, The (USA).nes": 22,
  "Adventures of Lolo (USA).nes": 23,
  "Adventures of Lolo 2 (USA).nes": 24,
  "Adventures of Lolo 3 (USA).nes": 25,
  "Adventures of Rad Gravity, The (USA).nes": 26,
  "Adventures of Rocky and Bullwinkle and Friends, The (USA).nes": 27,
  "Adventures of Tom Sawyer (USA).nes": 28,
  "After Burner (USA) (Unl).nes": 29,
  "Air Fortress (USA).nes": 30,
  "Airwolf (Japan) (Translated En).nes": 31,
  "Airwolf (USA).nes": 32,
  "Akira (Japan) (Translated En).nes": 33,
  "Akumajou Special - Boku Dracula-kun (Japan) (Translated En).nes": 34,
  "Al Unser Jr. Turbo Racing (USA).nes": 35,
  "Aladdin (Europe).nes": 36,
  "Alfred Chicken (USA).nes": 37,
  "Alien 3 (USA).nes": 38,
  "Alien Syndrome (USA) (Unl).nes": 39,
  "All-Pro Basketball (USA).nes": 40,
  "Alpha Mission (USA).nes": 41,
  "Amagon (USA).nes": 42,
  "American Dream (Japan) (Translated En).nes": 43,
  "American Gladiators (USA).nes": 44,
  "Ankoku Shinwa - Yamato Takeru Densetsu (Japan) (Translated En).nes": 45,
  "Anticipation (USA).nes": 46,
  "Arch Rivals - A Basketbrawl! (USA).nes": 47,
  "Archon (USA).nes": 48,
  "Arctic (Japan).nes": 49,
  "Argus (Japan).nes": 50,
  "Arkanoid (USA).nes": 51,
  "Arkanoid II (Japan).nes": 52,
  "Arkista's Ring (USA).nes": 53,
  "Armadillo (Japan) (Translated En).nes": 54,
  "Asterix (Europe) (En,Fr,De,Es,It).nes": 55,
  "Astro Fang - Super Machine (Japan) (Translated En).nes": 56,
  "Astro Robo Sasa (Japan).nes": 57,
  "Astyanax (USA).nes": 58,
  "Athena (USA).nes": 59,
  "Athletic World (USA).nes": 60,
  "Atlantis no Nazo (Japan).nes": 61,
  "Attack Animal Gakuen (Japan).nes": 62,
  "Attack of the Killer Tomatoes (USA).nes": 63,
  "B-Wings (Japan).nes": 64,
  "Babel no Tou (Japan).nes": 65,
  "Baby Boomer (USA) (Unl).nes": 66,
  "Back to the Future (USA).nes": 67,
  "Back to the Future Part II & III (USA).nes": 68,
  "Bad Dudes (USA).nes": 69,
  "Bad News Baseball (USA).nes": 70,
  "Bad Street Brawler (USA).nes": 71,
  "Ballblazer (Japan).nes": 72,
  "Balloon Fight (USA).nes": 73,
  "Baltron (Japan).nes": 74,
  "Banana (Japan).nes": 75,
  "Bandai Golf - Challenge Pebble Beach (USA).nes": 76,
  "Bandit Kings of Ancient China (USA).nes": 77,
  "Barbie (USA) (Rev A).nes": 78,
  "Bard's Tale, The (USA).nes": 79,
  "Barker Bill's Trick Shooting (USA).nes": 80,
  "Baseball (USA, Europe).nes": 81,
  "Baseball Simulator 1.000 (USA).nes": 82,
  "Baseball Stars (USA).nes": 83,
  "Baseball Stars II (USA).nes": 84,
  "Bases Loaded (USA) (Rev B).nes": 85,
  "Bases Loaded 3 (USA).nes": 86,
  "Bases Loaded 4 (USA).nes": 87,
  "Bases Loaded II - Second Season (USA).nes": 88,
  "Batman - Return of the Joker (USA).nes": 89,
  "Batman - The Video Game (USA).nes": 90,
  "Batman Returns (USA).nes": 91,
  "Battle Chess (USA).nes": 92,
  "Battle City (Japan).nes": 93,
  "Battle of Olympus, The (USA).nes": 94,
  "Battleship (USA).nes": 95,
  "Battletank (USA).nes": 96,
  "Battletoads (USA).nes": 97,
  "Battletoads-Double Dragon (USA).nes": 98,
  "Beauty and the Beast (Europe).nes": 99,
  "Bee 52 (USA) (Unl).nes": 100,
  "Beetlejuice (USA).nes": 101,
  "Best of the Best - Championship Karate (USA).nes": 102,
  "Bible Adventures (USA) (v1.4) (Unl).nes": 103,
  "Bible Buffet (USA) (v6.0) (Unl).nes": 104,
  "Big Nose Freaks Out (USA) (Unl).nes": 105,
  "Big Nose the Caveman (USA) (Unl).nes": 106,
  "Bigfoot (USA).nes": 107,
  "Bill & Ted's Excellent Video Game Adventure (USA).nes": 108,
  "Bill Elliott's NASCAR Challenge (USA).nes": 109,
  "Binary Land (Japan).nes": 110,
  "Bio Force Ape (Japan) (En) (Proto).nes": 111,
  "Bio Miracle Bokutte Upa (Japan).nes": 112,
  "Bio Senshi Dan - Increaser Tono Tatakai (Japan) (Translated En).nes": 113,
  "Bionic Commando (USA).nes": 114,
  "Bird Week (Japan).nes": 115,
  "Black Bass, The (USA).nes": 116,
  "Blackjack (USA) (Unl).nes": 117,
  "Blades of Steel (USA).nes": 118,
  "Blaster Master (USA).nes": 119,
  "Blodia Land - Puzzle Quest (Japan).nes": 120,
  "Bloody Warriors - Shan-Go no Gyakushuu (Japan) (Translated En).nes": 121,
  "Blue Marlin, The (USA).nes": 122,
  "Blues Brothers, The (USA).nes": 123,
  "Bo Jackson Baseball (USA).nes": 124,
  "Bokosuka Wars (Japan).nes": 125,
  "Bomberman (USA).nes": 126,
  "Bomberman II (USA).nes": 127,
  "Bonk's Adventure (USA).nes": 128,
  "Booby Kids (Japan).nes": 129,
  "Boulder Dash (USA).nes": 130,
  "Boy and His Blob, A - Trouble on Blobolonia (USA).nes": 131,
  "Bram Stoker's Dracula (USA).nes": 132,
  "Break Time - The National Pool Tour (USA).nes": 133,
  "BreakThru (USA).nes": 134,
  "Bubble Bath Babes (USA) (Unl).nes": 135,
  "Bubble Bobble (USA).nes": 136,
  "Bubble Bobble Part 2 (USA).nes": 137,
  "Bucky O'Hare (USA).nes": 138,
  "Bugs Bunny Birthday Blowout, The (USA).nes": 139,
  "Bugs Bunny Crazy Castle, The (USA).nes": 140,
  "Bump'n'Jump (USA).nes": 141,
  "Burai Fighter (USA).nes": 142,
  "BurgerTime (USA).nes": 143,
  "Cabal (USA).nes": 144,
  "Cadillac (Japan) (Translated En).nes": 145,
  "Caesars Palace (USA).nes": 146,
  "California Games (USA).nes": 147,
  "Caltron - 6 in 1 (USA) (Unl).nes": 148,
  "Capcom's Gold Medal Challenge '92 (USA).nes": 149,
  "Captain America and the Avengers (USA).nes": 150,
  "Captain Comic - The Adventure (USA) (Unl).nes": 151,
  "Captain Planet and the Planeteers (USA).nes": 152,
  "Captain Silver (Japan) (Translated En).nes": 153,
  "Captain Skyhawk (USA) (Rev A).nes": 154,
  "Captain Tsubasa Vol. II - Super Striker (Japan) (Translated En).nes": 155,
  "Casino Kid (USA).nes": 156,
  "Casino Kid II (USA).nes": 157,
  "Castelian (USA).nes": 158,
  "Castle Quest (Japan) (Translated En).nes": 159,
  "Castle of Deceit (USA) (Unl).nes": 160,
  "Castle of Dragon (USA).nes": 161,
  "Castlequest (USA).nes": 162,
  "Castlevania (USA) (Rev A).nes": 163,
  "Castlevania II - Simon's Quest (USA).nes": 164,
  "Castlevania III - Dracula's Curse (USA).nes": 165,
  "Cat Ninden Teyandee (Japan) (Translated En).nes": 166,
  "Caveman Games (USA).nes": 167,
  "Chack'n Pop (Japan).nes": 168,
  "Challenge of the Dragon (USA) (Unl).nes": 169,
  "Challenger (Japan).nes": 170,
  "Championship Bowling (USA).nes": 171,
  "Championship Lode Runner (Japan).nes": 172,
  "Championship Pool (USA).nes": 173,
  "Championship Rally (Europe).nes": 174,
  "Chaos World (Japan) (Translated En).nes": 175,
  "Cheetahmen II (USA) (Unl).nes": 176,
  "Chessmaster, The (USA).nes": 177,
  "Chester Field - Ankoku Shin e no Chousen (Japan) (Translated En).nes": 178,
  "Chiisana Obake - Acchi Socchi Kocchi (Japan).nes": 179,
  "Chiller (USA) (Unl).nes": 180,
  "Chip 'n Dale Rescue Rangers (USA).nes": 181,
  "Chip 'n Dale Rescue Rangers 2 (USA).nes": 182,
  "Choplifter (Japan) (En) (Rev 1).nes": 183,
  "Choujin Sentai - Jetman (Japan).nes": 184,
  "Chris Evert & Ivan Lendl in Top Players' Tennis (USA).nes": 185,
  "Chubby Cherub (USA).nes": 186,
  "Chuuka Taisen (Japan) (Translated En).nes": 187,
  "Circus Caper (USA).nes": 188,
  "Circus Charlie (Japan).nes": 189,
  "City Connection (USA).nes": 190,
  "Clash at Demonhead (USA).nes": 191,
  "Classic Concentration (USA).nes": 192,
  "Cliffhanger (USA).nes": 193,
  "Clu Clu Land (World).nes": 194,
  "Cobra Command (USA).nes": 195,
  "Cobra Triangle (USA).nes": 196,
  "Cocoron (Japan) (Translated En).nes": 197,
  "Code Name - Viper (USA).nes": 198,
  "Color a Dinosaur (USA).nes": 199,
  "Columbus - Ougon no Yoake (Japan) (Translated En).nes": 200,
  "Commando (USA).nes": 201,
  "Conan (USA).nes": 202,
  "Conflict (USA).nes": 203,
  "Conquest of the Crystal Palace (USA).nes": 204,
  "Contra (USA).nes": 205,
  "Contra Force (USA).nes": 206,
  "Cool World (USA).nes": 207,
  "Corvette ZR-1 Challenge (Europe).nes": 208,
  "Cosmic Epsilon (Japan).nes": 209,
  "Cosmic Spacehead (Europe) (En,Fr,De,Es) (Unl).nes": 210,
  "Cosmo Police Galivan (Japan) (Translated En).nes": 211,
  "Cowboy Kid (USA).nes": 212,
  "Crackout (Europe).nes": 213,
  "Crash 'n' the Boys - Street Challenge (USA).nes": 214,
  "Crazy Climber (Japan).nes": 215,
  "Crisis Force (Japan).nes": 216,
  "Crystal Mines (USA) (Unl).nes": 217,
  "Crystalis (USA).nes": 218,
  "Cyber Stadium Series - Base Wars (USA).nes": 219,
  "Cyberball (USA).nes": 220,
  "Cybernoid - The Fighting Machine (USA).nes": 221,
  "Cycle Race - Road Man (Japan).nes": 222,
  "Daimeiro - Meikyuu no Tatsujin (Japan) (Translated En).nes": 223,
  "Daisenryaku (Japan) (Translated En).nes": 224,
  "Dance Aerobics (USA).nes": 225,
  "Danny Sullivan's Indy Heat (USA).nes": 226,
  "Dark Lord (Japan) (Translated En).nes": 227,
  "Darkman (USA).nes": 228,
  "Darkwing Duck (USA).nes": 229,
  "Dash Galaxy in the Alien Asylum (USA).nes": 230,
  "Day Dreamin' Davey (USA).nes": 231,
  "Days of Thunder (USA).nes": 232,
  "Deadly Towers (USA).nes": 233,
  "Death Race (USA) (Unl).nes": 234,
  "Deathbots (USA) (Rev 1) (Unl).nes": 235,
  "Deblock (Japan).nes": 236,
  "Deep Dungeon IV - Kuro no Youjutsushi (Japan) (Translated En).nes": 237,
  "Defender II (USA).nes": 238,
  "Defender of the Crown (USA).nes": 239,
  "Defenders of Dynatron City (USA).nes": 240,
  "Deja Vu (USA).nes": 241,
  "Demon Sword - Release the Power (USA).nes": 242,
  "Desert Commander (USA).nes": 243,
  "Destination Earthstar (USA).nes": 244,
  "Destiny of an Emperor (USA).nes": 245,
  "Devil Man (Japan) (Translated En).nes": 246,
  "Devil World (Europe).nes": 247,
  "Dezaemon (Japan) (Translated En).nes": 248,
  "Dick Tracy (USA).nes": 249,
  "Die Hard (USA).nes": 250,
  "Dig Dug (Japan).nes": 251,
  "Dig Dug II - Trouble in Paradise (USA).nes": 252,
  "Digger - The Legend of the Lost City (USA).nes": 253,
  "Dirty Harry (USA).nes": 254,
  "Dizzy the Adventurer (USA) (Aladdin Compact Cartridge) (Unl).nes": 255,
  "Don Doko Don (Japan).nes": 256,
  "Donald Land (Japan).nes": 257,
  "Donkey Kong (World) (Rev A).nes": 258,
  "Donkey Kong 3 (World).nes": 259,
  "Donkey Kong Classics (USA, Europe).nes": 260,
  "Donkey Kong Jr. (World) (Rev A).nes": 261,
  "Donkey Kong Jr. Math (USA, Europe).nes": 262,
  "Door Door (Japan).nes": 263,
  "Doraemon (Japan) (Rev A).nes": 264,
  "Doraemon - Giga Zombie no Gyakushuu (Japan) (Translated En).nes": 265,
  "Double Dare (USA).nes": 266,
  "Double Dragon (USA).nes": 267,
  "Double Dragon II - The Revenge (USA) (Rev A).nes": 268,
  "Double Dragon III - The Sacred Stones (USA).nes": 269,
  "Double Dribble (USA) (Rev A).nes": 270,
  "Double Strike - Aerial Attack Force (USA) (v1.1) (Unl).nes": 271,
  "Dough Boy (Japan).nes": 272,
  "Downtown Special - Kunio-kun no Jidaigeki Da yo Zenin Shuugou! (Japan) (Translated En).nes": 273,
  "Dr. Chaos (USA).nes": 274,
  "Dr. Jekyll and Mr. Hyde (USA).nes": 275,
  "Dr. Mario (Japan, USA) (Rev A).nes": 276,
  "Dragon Ball - Daimaou Fukkatsu (Japan) (Translated En).nes": 277,
  "Dragon Ball Z - Kyoushuu! Saiya Jin (Japan) (Translated En).nes": 278,
  "Dragon Ball Z Gaiden - Saiya Jin Zetsumetsu Keikaku (Japan) (Translated En).nes": 279,
  "Dragon Ball Z III - Ressen Jinzou Ningen (Japan) (Translated En).nes": 280,
  "Dragon Buster (Japan).nes": 281,
  "Dragon Buster II - Yami no Fuuin (Japan).nes": 282,
  "Dragon Fighter (USA).nes": 283,
  "Dragon Power (USA).nes": 284,
  "Dragon Scroll - Yomigaerishi Maryuu (Japan) (Translated En).nes": 285,
  "Dragon Spirit - The New Legend (USA).nes": 286,
  "Dragon Warrior (USA) (Rev A).nes": 287,
  "Dragon Warrior II (USA).nes": 288,
  "Dragon Warrior III (USA).nes": 289,
  "Dragon Warrior IV (USA).nes": 290,
  "Dragon's Lair (USA).nes": 291,
  "Dream Master (Japan) (Translated En).nes": 292,
  "Dropzone (Europe).nes": 293,
  "Duck Hunt (World).nes": 294,
  "DuckTales (USA).nes": 295,
  "DuckTales 2 (USA).nes": 296,
  "Dudes With Attitude (USA) (Rev 1) (Unl).nes": 297,
  "Dungeon Magic - Sword of the Elements (USA).nes": 298,
  "Dusty Diamond's All-Star Softball (USA).nes": 299,
  "Dynablaster (Europe).nes": 300,
  "Dynamite Bowl (Japan) (Rev A).nes": 301,
  "Dynowarz - Destruction of Spondylus (USA).nes": 302,
  "Eggerland - Meikyuu no Fukkatsu (Japan) (Translated En).nes": 303,
  "Elevator Action (USA).nes": 304,
  "Eliminator Boat Duel (USA).nes": 305,
  "Elite (Europe) (En,Fr,De).nes": 306,
  "Elysion (Japan) (Translated En).nes": 307,
  "Empereur, L' (USA).nes": 308,
  "Eric Cantona Football Challenge - Goal! 2 (Europe).nes": 309,
  "Esper Bouken Tai (Japan) (Translated En).nes": 310,
  "Esper Dream 2 - Aratanaru Tatakai (Japan) (Translated En).nes": 311,
  "Excitebike (Japan, USA).nes": 312,
  "Exciting Boxing (Japan).nes": 313,
  "Exed Exes (Japan).nes": 314,
  "Exerion (Japan) (En) (Proto).nes": 315,
  "Exodus - Journey to the Promised Land (USA) (v5.0) (Unl).nes": 316,
  "F-1 Race (Japan).nes": 317,
  "F-117A - Stealth Fighter (USA).nes": 318,
  "F-15 Strike Eagle (USA).nes": 319,
  "F15 City War (USA) (v1.1) (Unl).nes": 320,
  "Famicom Wars (Japan) (Rev 0B) (Translated En).nes": 321,
  "Family Feud (USA).nes": 322,
  "Fantastic Adventures of Dizzy, The (USA) (Unl).nes": 323,
  "Fantasy Zone (USA) (Unl).nes": 324,
  "Fantasy Zone 2 - Opa-Opa no Namida (Japan).nes": 325,
  "Faria - A World of Mystery & Danger! (USA).nes": 326,
  "Faxanadu (USA) (Rev A).nes": 327,
  "Felix the Cat (USA).nes": 328,
  "Ferrari Grand Prix Challenge (USA).nes": 329,
  "Fester's Quest (USA).nes": 330,
  "Field Combat (Japan).nes": 331,
  "Final Fantasy (USA).nes": 332,
  "Final Fantasy II (Japan) (Translated En).nes": 333,
  "Final Fantasy III (Japan) (Translated En).nes": 334,
  "Final Lap (Japan).nes": 335,
  "Fire 'n Ice (USA).nes": 336,
  "Fire Emblem (Japan) (Translated En).nes": 337,
  "Fire Emblem Gaiden (Japan) (Translated En).nes": 338,
  "Fire Hawk (USA) (Unl).nes": 339,
  "Fisher-Price - Firehouse Rescue (USA).nes": 340,
  "Fisher-Price - I Can Remember (USA).nes": 341,
  "Fisher-Price - Perfect Fit (USA).nes": 342,
  "Fist of the North Star (USA).nes": 343,
  "Flappy (Japan).nes": 344,
  "Flight of the Intruder (USA).nes": 345,
  "Flintstones, The - The Rescue of Dino & Hoppy (USA).nes": 346,
  "Flintstones, The - The Surprise at Dinosaur Peak! (USA).nes": 347,
  "Flipull - An Exciting Cube Game (Japan).nes": 348,
  "Flying Dragon - The Secret Scroll (USA).nes": 349,
  "Flying Hero (Japan).nes": 350,
  "Flying Warriors (USA).nes": 351,
  "Formation Z (Japan) (Rev A).nes": 352,
  "Formula 1 Sensation (Europe).nes": 353,
  "Formula One - Built to Win (USA).nes": 354,
  "Foton - The Ultimate Game on Planet Earth (Japan) (Translated En).nes": 355,
  "Fox's Peter Pan & the Pirates - The Revenge of Captain Hook (USA).nes": 356,
  "Frankenstein - The Monster Returns (USA).nes": 357,
  "Freedom Force (USA).nes": 358,
  "Friday the 13th (USA).nes": 359,
  "Front Line (Japan).nes": 360,
  "Fudou Myouou Den (Japan) (Translated En).nes": 361,
  "Fun House (USA).nes": 362,
  "Fushigi no Umi no Nadia (Japan) (Translated En).nes": 363,
  "Fuzzical Fighter (Japan) (Translated En).nes": 364,
  "G.I. Joe - A Real American Hero (USA).nes": 365,
  "G.I. Joe - The Atlantis Factor (USA).nes": 366,
  "Galactic Crusader (USA) (Unl).nes": 367,
  "Galaga - Demons of Death (USA).nes": 368,
  "Galaxian (Japan) (Rev A).nes": 369,
  "Galaxy 5000 (USA).nes": 370,
  "Game Party (Japan).nes": 371,
  "Ganbare Goemon! - Karakuri Douchuu (Japan) (Translated En).nes": 372,
  "Garfield - A Week of Garfield (Japan).nes": 373,
  "Gargoyle's Quest II (USA).nes": 374,
  "Gauntlet (USA).nes": 375,
  "Gauntlet II (USA).nes": 376,
  "Gegege no Kitarou - Youkai Daimakyou (Japan) (Translated En).nes": 377,
  "Gegege no Kitarou 2 - Youkai Gundan no Chousen (Japan) (Translated En).nes": 378,
  "Geimos (Japan).nes": 379,
  "Gekitotsu Yonku Battle (Japan).nes": 380,
  "Gemfire (USA).nes": 381,
  "Genghis Khan (USA).nes": 382,
  "George Foreman's KO Boxing (USA).nes": 383,
  "Getsufuu Maden (Japan) (Translated En).nes": 384,
  "Ghostbusters (USA).nes": 385,
  "Ghostbusters II (USA).nes": 386,
  "Ghosts'n Goblins (USA).nes": 387,
  "Ghoul School (USA).nes": 388,
  "Goal! (USA).nes": 389,
  "Goal! Two (USA).nes": 390,
  "Godzilla - Monster of Monsters! (USA).nes": 391,
  "Godzilla 2 - War of the Monsters (USA).nes": 392,
  "Golf (USA).nes": 393,
  "Golf Grand Slam (USA).nes": 394,
  "Golgo 13 - Top Secret Episode (USA).nes": 395,
  "Goonies (Japan).nes": 396,
  "Goonies II, The (USA).nes": 397,
  "Gorby no Pipeline Daisakusen (Japan).nes": 398,
  "Gotcha! - The Sport! (USA).nes": 399,
  "Gradius (USA).nes": 400,
  "Gradius II (Japan).nes": 401,
  "Grand Master (Japan) (Translated En).nes": 402,
  "Great Deal (Japan).nes": 403,
  "Great Waldo Search, The (USA).nes": 404,
  "Greg Norman's Golf Power (USA).nes": 405,
  "Gremlins 2 - The New Batch (USA).nes": 406,
  "Guardian Legend, The (USA).nes": 407,
  "Guerrilla War (USA).nes": 408,
  "Gumshoe (USA, Europe).nes": 409,
  "Gun Nac (USA).nes": 410,
  "Gun.Smoke (USA).nes": 411,
  "Gyrodine (Japan).nes": 412,
  "Gyromite (World).nes": 413,
  "Gyruss (USA).nes": 414,
  "Hammerin' Harry (Europe).nes": 415,
  "Harlem Globetrotters (USA).nes": 416,
  "Hatris (USA).nes": 417,
  "Heavy Barrel (USA).nes": 418,
  "Heavy Shreddin' (USA).nes": 419,
  "Hello Kitty World (Japan) (Translated En).nes": 420,
  "Hello Kitty no Ohanabatake (Japan).nes": 421,
  "Heracles no Eikou - Toujin Makyou Den (Japan) (Translated En).nes": 422,
  "Heracles no Eikou II - Titan no Metsubou (Japan) (Translated En).nes": 423,
  "Higemaru Makai-jima - Nanatsu no Shima Daibouken (Japan) (Translated En).nes": 424,
  "High Speed (USA).nes": 425,
  "Hinotori - Houou Hen - Gaou no Bouken (Japan) (Translated En).nes": 426,
  "Hirake! Ponkikki (Japan) (Translated En).nes": 427,
  "Hogan's Alley (World).nes": 428,
  "Hokuto no Ken (Japan).nes": 429,
  "Hollywood Squares (USA).nes": 430,
  "Holy Diver (Japan).nes": 431,
  "Home Alone (USA) (Rev A).nes": 432,
  "Home Alone 2 - Lost in New York (USA).nes": 433,
  "Honoo no Toukyuuji - Dodge Danpei (Japan) (Translated En).nes": 434,
  "Honoo no Toukyuuji - Dodge Danpei 2 (Japan) (Translated En).nes": 435,
  "Hook (USA).nes": 436,
  "Hoops (USA).nes": 437,
  "Hottarman no Chitei Tanken (Japan) (Translated En).nes": 438,
  "Houma ga Toki (Japan).nes": 439,
  "Hudson Hawk (USA).nes": 440,
  "Hunt for Red October, The (USA) (Rev A).nes": 441,
  "Hyaku no Sekai no Monogatari - The Tales on a Watery Wilderness (Japan) (Translated En).nes": 442,
  "Hydlide (USA).nes": 443,
  "Hyper Sports (Japan) (Rev 1).nes": 444,
  "Ice Climber (USA, Europe).nes": 445,
  "Ice Hockey (USA).nes": 446,
  "Ikari Warriors (USA) (Rev A).nes": 447,
  "Ikari Warriors II - Victory Road (USA).nes": 448,
  "Ikari Warriors III - The Rescue (USA).nes": 449,
  "Ike Ike! Nekketsu Hockey-bu - Subette Koronde Dairantou (Japan) (Translated En).nes": 450,
  "Ikinari Musician (Japan).nes": 451,
  "Ikki (Japan).nes": 452,
  "Image Fight (USA).nes": 453,
  "Immortal, The (USA).nes": 454,
  "Impossible Mission II (USA) (Unl).nes": 455,
  "Incredible Crash Dummies, The (USA).nes": 456,
  "Indiana Jones and the Last Crusade (USA) (Taito).nes": 457,
  "Indiana Jones and the Last Crusade (USA) (UBI Soft).nes": 458,
  "Indiana Jones and the Temple of Doom (USA) (Rev A).nes": 459,
  "Infiltrator (USA).nes": 460,
  "Insector X (Japan).nes": 461,
  "Iron Tank - The Invasion of Normandy (USA).nes": 462,
  "Isolated Warrior (USA).nes": 463,
  "Ivan 'Ironman' Stewart's Super Off Road (USA).nes": 464,
  "J.League Fighting Soccer - The King of Ace Strikers (Japan).nes": 465,
  "JJ (Japan).nes": 466,
  "Jack Nicklaus' Greatest 18 Holes of Major Championship Golf (USA).nes": 467,
  "Jackal (USA).nes": 468,
  "Jackie Chan's Action Kung Fu (USA).nes": 469,
  "Jajamaru Gekimaden - Maboroshi no Kinmajou (Japan) (Translated En).nes": 470,
  "Jajamaru no Daibouken (Japan) (Translated En).nes": 471,
  "James Bond Jr (USA).nes": 472,
  "Jaws (USA).nes": 473,
  "Jeopardy! (USA) (Rev A).nes": 474,
  "Jeopardy! 25th Anniversary Edition (USA).nes": 475,
  "Jeopardy! Junior Edition (USA).nes": 476,
  "Jesus - Kyoufu no Bio Monster (Japan) (Translated En).nes": 477,
  "Jetsons, The - Cogswell's Caper (USA).nes": 478,
  "Jikuu Yuuden - Debias (Japan) (Translated En).nes": 479,
  "Jimmy Connors Tennis (USA).nes": 480,
  "Joe & Mac (USA).nes": 481,
  "John Elway's Quarterback (USA).nes": 482,
  "Jordan vs Bird - One On One (USA).nes": 483,
  "Joshua & the Battle of Jericho (USA) (v6.0) (Unl).nes": 484,
  "Journey to Silius (USA).nes": 485,
  "Joust (USA).nes": 486,
  "Joy Mech Fight (Japan) (Translated En).nes": 487,
  "Jumbo Ozaki no Hole in One Professional (Japan).nes": 488,
  "Jungle Book, The (USA).nes": 489,
  "Jurassic Park (USA).nes": 490,
  "Just Breed (Japan) (Translated En).nes": 491,
  "Juuouki (Japan).nes": 492,
  "Kabuki - Quantum Fighter (USA).nes": 493,
  "Kaguya Hime Densetsu (Japan) (Translated En).nes": 494,
  "Kaijuu Monogatari (Japan) (Translated En).nes": 495,
  "Kaiketsu Yancha Maru 2 - Karakuri Land (Japan) (Translated En).nes": 496,
  "Kaiketsu Yancha Maru 3 - Taiketsu! Zouringen (Japan) (Translated En).nes": 497,
  "Kanshakudama Nage Kantarou no Toukaidou Gojuusan Tsugi (Japan) (Translated En).nes": 498,
  "Karate Champ (USA) (Rev A).nes": 499,
  "Karate Kid, The (USA).nes": 500,
  "Karateka (Japan).nes": 501,
  "Karnov (USA).nes": 502,
  "Kekkyoku Nankyoku Daibouken (Japan).nes": 503,
  "Kero Kero Keroppi no Daibouken (Japan) (Translated En).nes": 504,
  "Kero Kero Keroppi no Daibouken 2 - Donuts Ike wa Oosawagi! (Japan) (Translated En).nes": 505,
  "Keroppi to Keroriinu no Splash Bomb! (Japan) (Translated En).nes": 506,
  "Kick Master (USA).nes": 507,
  "Kick Off (Europe).nes": 508,
  "Kickle Cubicle (USA).nes": 509,
  "Kid Icarus (USA, Europe).nes": 510,
  "Kid Klown in Night Mayor World (USA).nes": 511,
  "Kid Kool and the Quest for the Seven Wonder Herbs (USA).nes": 512,
  "Kid Niki - Radical Ninja (USA) (Rev A).nes": 513,
  "King Kong 2 - Ikari no Megaton Punch (Japan).nes": 514,
  "King Neptune's Adventure (USA) (Unl).nes": 515,
  "King of Kings, The (USA) (v5.0) (Unl).nes": 516,
  "King's Knight (USA).nes": 517,
  "King's Quest V (USA).nes": 518,
  "Kings of the Beach - Professional Beach Volleyball (USA).nes": 519,
  "Kirby's Adventure (USA) (Rev A).nes": 520,
  "Kiwi Kraze - A Bird-Brained Adventure! (USA).nes": 521,
  "Klash Ball (USA).nes": 522,
  "Klax (USA) (Unl).nes": 523,
  "Knight Rider (USA).nes": 524,
  "Konami Hyper Soccer (Europe).nes": 525,
  "Kouryuu Densetsu Villgust Gaiden (Japan) (Translated En).nes": 526,
  "Krazy Kreatures (USA) (Unl).nes": 527,
  "Krion Conquest, The (USA).nes": 528,
  "Krusty's Fun House (USA).nes": 529,
  "Kujaku Ou (Japan) (Translated En).nes": 530,
  "Kujaku Ou II (Japan) (Translated En).nes": 531,
  "Kung Fu (1985-10)(Nintendo)(JP-US).nes": 532,
  "Kung Fu (Japan, USA).nes": 533,
  "Kung-Fu Heroes (USA).nes": 534,
  "Kunio-kun no Nekketsu Soccer League (Japan) (Translated En).nes": 535,
  "Kyouryuu Sentai Juuranger (Japan) (Translated En).nes": 536,
  "Labyrinth (Japan) (Translated En).nes": 537,
  "Laser Invasion (USA).nes": 538,
  "Last Action Hero (USA).nes": 539,
  "Last Ninja, The (USA).nes": 540,
  "Last Starfighter, The (USA).nes": 541,
  "Layla (Japan).nes": 542,
  "Lee Trevino's Fighting Golf (USA).nes": 543,
  "Legacy of the Wizard (USA).nes": 544,
  "Legend of Kage, The (USA).nes": 545,
  "Legend of Prince Valiant, The (Europe).nes": 546,
  "Legend of Zelda II, The - The Adventure of Link (USA).nes": 547,
  "Legend of Zelda, The (USA) (Rev A).nes": 548,
  "Legend of the Ghost Lion (USA).nes": 549,
  "Legendary Wings (USA).nes": 550,
  "Legends of the Diamond - The Baseball Championship Game (USA).nes": 551,
  "Lemmings (USA).nes": 552,
  "Lethal Weapon (USA).nes": 553,
  "Life Force (USA).nes": 554,
  "Linus Spacehead's Cosmic Crusade (USA) (En,Fr,De,Es) (Unl).nes": 555,
  "Lion King, The (Europe).nes": 556,
  "Little League Baseball - Championship Series (USA).nes": 557,
  "Little Mermaid, The (USA).nes": 558,
  "Little Nemo - The Dream Master (USA).nes": 559,
  "Little Ninja Brothers (USA).nes": 560,
  "Little Samson (USA).nes": 561,
  "Lode Runner (USA).nes": 562,
  "Lone Ranger, The (USA).nes": 563,
  "Loopz (USA).nes": 564,
  "Lost Word of Jenny - Ushinawareta Message (Japan).nes": 565,
  "Lot Lot (Japan).nes": 566,
  "Low G Man - The Low Gravity Man (USA).nes": 567,
  "Lunar Pool (USA).nes": 568,
  "Lupin Sansei - Pandora no Isan (Japan) (Translated En).nes": 569,
  "M.C. Kids (USA).nes": 570,
  "M.U.L.E. (USA).nes": 571,
  "M.U.S.C.L.E. - Tag Team Match (USA).nes": 572,
  "Mach Rider (Japan, USA) (Rev A).nes": 573,
  "Mad City (Japan) (Translated En).nes": 574,
  "Mad Max (USA).nes": 575,
  "Madoola no Tsubasa (Japan).nes": 576,
  "Mafat Conspiracy, The (USA).nes": 577,
  "Magic Darts (USA).nes": 578,
  "Magic Johnson's Fast Break (USA).nes": 579,
  "Magic of Scheherazade, The (USA).nes": 580,
  "Magical Doropie (Japan) (Translated En).nes": 581,
  "Magician (USA).nes": 582,
  "Magmax (USA).nes": 583,
  "Magnum Kikiippatsu - Empire City - 1931 (Japan).nes": 584,
  "Major League Baseball (USA) (Rev A).nes": 585,
  "Majou Densetsu II - Daimashikyou Galious (Japan) (Translated En).nes": 586,
  "Maniac Mansion (USA).nes": 587,
  "Mappy (Japan).nes": 588,
  "Mappy-Land (USA).nes": 589,
  "Marble Madness (USA).nes": 590,
  "Mario Bros. (World).nes": 591,
  "Mario Is Missing! (USA).nes": 592,
  "Mario's Time Machine (USA).nes": 593,
  "Master Chu and the Drunkard Hu (USA) (Unl).nes": 594,
  "Maxi 15 (USA) (Rev 1) (Unl).nes": 595,
  "Mechanized Attack (USA).nes": 596,
  "Mega Man (USA).nes": 597,
  "Mega Man 2 (USA).nes": 598,
  "Mega Man 3 (USA).nes": 599,
  "Mega Man 4 (USA) (Rev A).nes": 600,
  "Mega Man 5 (USA).nes": 601,
  "Mega Man 6 (USA).nes": 602,
  "Menace Beach (USA) (Unl).nes": 603,
  "Mendel Palace (USA).nes": 604,
  "Mermaids of Atlantis - The Riddle of the Magic Bubble (USA) (Unl).nes": 605,
  "Metal Fighter (USA) (Unl).nes": 606,
  "Metal Gear (USA).nes": 607,
  "Metal Mech - Man & Machine (USA).nes": 608,
  "Metal Storm (USA).nes": 609,
  "Metro-Cross (Japan).nes": 610,
  "Metroid (USA).nes": 611,
  "MiG 29 - Soviet Fighter (USA) (Unl).nes": 612,
  "Michael Andretti's World GP (USA).nes": 613,
  "Mickey Mouse 3 - Yume Fuusen (Japan) (Translated En).nes": 614,
  "Mickey Mousecapade (USA).nes": 615,
  "Mickey's Adventure in Numberland (USA).nes": 616,
  "Mickey's Safari in Letterland (USA).nes": 617,
  "Micro Machines (USA) (Unl).nes": 618,
  "Might & Magic - Secret of the Inner Sanctum (USA).nes": 619,
  "Mighty Bomb Jack (USA).nes": 620,
  "Mighty Final Fight (USA).nes": 621,
  "Mike Tyson's Punch-Out!! (Japan, USA) (Rev A).nes": 622,
  "Millipede (USA).nes": 623,
  "Milon's Secret Castle (USA).nes": 624,
  "Minelvaton Saga (Japan) (Translated En).nes": 625,
  "Mini Putt (Japan).nes": 626,
  "Minna no Taabou no Nakayoshi Daisakusen (Japan).nes": 627,
  "Miracle Ropit's Adventure in 2100 (Japan).nes": 628,
  "Mirai Senshi - Lios (Japan) (Translated En).nes": 629,
  "Mirai Shinwa Jarvas (Japan) (Translated En).nes": 630,
  "Mission Cobra (USA) (Unl).nes": 631,
  "Mission Impossible (USA).nes": 632,
  "Mitsume ga Tooru (Japan) (Translated En).nes": 633,
  "Moai-kun (Japan).nes": 634,
  "Monopoly (USA).nes": 635,
  "Monster Party (USA).nes": 636,
  "Monster Truck Rally (USA).nes": 637,
  "Monster in My Pocket (USA).nes": 638,
  "Moon Crystal (Japan) (Translated En).nes": 639,
  "Moon Ranger (USA) (Unl).nes": 640,
  "Motocross Champion (Japan) (Translated En).nes": 641,
  "Motor City Patrol (USA).nes": 642,
  "Mottomo Abunai Deka (Japan) (Translated En).nes": 643,
  "Mouryou Senki Madara (Japan) (Translated En).nes": 644,
  "Mr. Gimmick (Europe).nes": 645,
  "Ms. Pac-Man (USA).nes": 646,
  "Muppet Adventure - Chaos at the Carnival (USA).nes": 647,
  "Musashi no Bouken (Japan) (Translated En).nes": 648,
  "Mutant Virus, The - Crisis in a Computer World (USA).nes": 649,
  "Mystery Quest (USA).nes": 650,
  "NARC (USA).nes": 651,
  "NES Open Tournament Golf (USA).nes": 652,
  "NES Play Action Football (USA).nes": 653,
  "NFL (USA).nes": 654,
  "Nagagutsu o Haita Neko - Sekai Isshuu 80 Nichi Daibouken (Japan).nes": 655,
  "Nakayoshi to Issho (Japan) (Translated En).nes": 656,
  "Nekketsu! Street Basket - Ganbare Dunk Heroes (Japan) (Translated En).nes": 657,
  "New Ghostbusters II (Europe).nes": 658,
  "New Zealand Story, The (Europe).nes": 659,
  "Nigel Mansell's World Championship Challenge (USA).nes": 660,
  "Nightmare on Elm Street, A (USA).nes": 661,
  "Nightshade (USA).nes": 662,
  "Niji no Silk Road (Japan) (Translated En).nes": 663,
  "Ninja Crusaders (USA).nes": 664,
  "Ninja Gaiden (USA).nes": 665,
  "Ninja Gaiden II - The Dark Sword of Chaos (USA).nes": 666,
  "Ninja Gaiden III - The Ancient Ship of Doom (USA).nes": 667,
  "Ninja Hattori-kun - Ninja wa Syugyou de Gozaru (Japan).nes": 668,
  "Ninja Jajamaru - Ginga Daisakusen (Japan) (Translated En).nes": 669,
  "Ninja Jajamaru-kun (Japan).nes": 670,
  "Ninja Kid (USA).nes": 671,
  "Ninja-kun - Ashura no Shou (Japan) (Translated En).nes": 672,
  "Ninja-kun - Majou no Bouken (Japan) (Rev 1).nes": 673,
  "Nintendo World Championships 1990 (USA).nes": 674,
  "Nintendo World Cup (USA).nes": 675,
  "Noah's Ark (Europe).nes": 676,
  "Nobunaga's Ambition (USA).nes": 677,
  "Nobunaga's Ambition II (USA).nes": 678,
  "North and South (USA).nes": 679,
  "Nuts & Milk (Japan).nes": 680,
  "Oishinbo (Japan) (Translated En).nes": 681,
  "Onyanko Town (Japan).nes": 682,
  "Operation Secret Storm (USA) (Unl).nes": 683,
  "Operation Wolf (USA) (Rev 0A).nes": 684,
  "Orb 3D (USA).nes": 685,
  "Othello (USA).nes": 686,
  "Over Horizon (Europe).nes": 687,
  "Overlord (USA).nes": 688,
  "P'radikus Conflict, The (USA) (Unl).nes": 689,
  "P.O.W. - Prisoners of War (USA).nes": 690,
  "Pac-Land (Japan).nes": 691,
  "Pac-Man (USA) (Namco).nes": 692,
  "Pac-Man (USA) (Tengen).nes": 693,
  "Pac-Mania (USA) (Unl).nes": 694,
  "Pachicom (Japan).nes": 695,
  "Palamedes (USA).nes": 696,
  "Palamedes II - Star Twinkle, Hoshi no Mabataki (Japan).nes": 697,
  "Panic Restaurant (USA).nes": 698,
  "Paperboy (USA).nes": 699,
  "Paperboy 2 (USA).nes": 700,
  "Parallel World (Japan).nes": 701,
  "Parodius (Europe).nes": 702,
  "Peepar Time (Japan).nes": 703,
  "Penguin-kun Wars (Japan).nes": 704,
  "Perfect Bowling (Japan).nes": 705,
  "Perman Part 2 - Himitsu Kessha Madoodan o Taose! (Japan) (Translated En).nes": 706,
  "Pescatore (Japan) (Proto).nes": 707,
  "Pesterminator (USA) (Unl).nes": 708,
  "Phantom Fighter (USA).nes": 709,
  "Pictionary - The Game of Video Quick Draw (USA).nes": 710,
  "Pin-Bot (USA).nes": 711,
  "Pinball (World).nes": 712,
  "Pinball Quest (USA).nes": 713,
  "Pipe Dream (USA).nes": 714,
  "Pirates! (USA).nes": 715,
  "Pizza Pop! (Japan).nes": 716,
  "Platoon (USA) (Rev A).nes": 717,
  "Pooyan (Japan).nes": 718,
  "Popeye (World) (Rev A).nes": 719,
  "Portopia Renzoku Satsujin Jiken (Japan) (Translated En).nes": 720,
  "Power Blade (USA).nes": 721,
  "Power Blade 2 (USA).nes": 722,
  "Power Blazer (Japan).nes": 723,
  "Power Punch II (USA).nes": 724,
  "Power Soccer (Japan).nes": 725,
  "Predator (USA).nes": 726,
  "Prince of Persia (USA).nes": 727,
  "Princess Tomato in Salad Kingdom (USA).nes": 728,
  "Pro Sport Hockey (USA).nes": 729,
  "Pro Wrestling (USA) (Rev A).nes": 730,
  "Punch-Out!! (USA).nes": 731,
  "Punisher, The (USA).nes": 732,
  "Puss n Boots - Pero's Great Adventure (USA).nes": 733,
  "Puyo Puyo (Japan).nes": 734,
  "Puzslot (Japan).nes": 735,
  "Puzzle (USA) (Unl).nes": 736,
  "Puzznic (USA).nes": 737,
  "Pyramid (USA) (Rev 1) (Unl).nes": 738,
  "Q-bert (USA).nes": 739,
  "Qix (USA).nes": 740,
  "Quarth (Japan).nes": 741,
  "Quattro Adventure (USA) (Unl).nes": 742,
  "Quattro Arcade (USA) (Unl).nes": 743,
  "Quattro Sports (USA) (Unl).nes": 744,
  "R.B.I. Baseball (USA).nes": 745,
  "R.B.I. Baseball 2 (USA) (Unl).nes": 746,
  "R.B.I. Baseball 3 (USA) (Unl).nes": 747,
  "R.C. Pro-Am (USA) (Rev A).nes": 748,
  "R.C. Pro-Am II (USA).nes": 749,
  "Race America (USA).nes": 750,
  "Racket Attack (USA).nes": 751,
  "Rackets & Rivals (Europe).nes": 752,
  "Rad Racer (USA).nes": 753,
  "Rad Racer II (USA).nes": 754,
  "Rad Racket - Deluxe Tennis II (USA) (Unl).nes": 755,
  "Radia Senki - Reimei Hen (Japan) (Translated En).nes": 756,
  "Raid 2020 (USA) (Unl).nes": 757,
  "Raid on Bungeling Bay (USA).nes": 758,
  "Rainbow Islands (USA).nes": 759,
  "Rally Bike (USA).nes": 760,
  "Rambo (USA) (Rev A).nes": 761,
  "Rampage (USA).nes": 762,
  "Rampart (USA).nes": 763,
  "Remote Control (USA).nes": 764,
  "Ren & Stimpy Show, The - Buckeroo$! (USA).nes": 765,
  "Renegade (USA).nes": 766,
  "Rescue - The Embassy Mission (USA).nes": 767,
  "Ring King (USA).nes": 768,
  "River City Ransom (USA).nes": 769,
  "Road Fighter (Europe).nes": 770,
  "Road Runner (USA) (Unl).nes": 771,
  "RoadBlasters (USA).nes": 772,
  "Robin Hood - Prince of Thieves (USA) (Rev A).nes": 773,
  "Robo Warrior (USA).nes": 774,
  "RoboCop (USA).nes": 775,
  "RoboCop 2 (USA) (Rev A).nes": 776,
  "RoboCop 3 (USA).nes": 777,
  "Robocco Wars (Japan).nes": 778,
  "Robodemons (USA) (Unl).nes": 779,
  "Rock 'n' Ball (USA).nes": 780,
  "Rocket Ranger (USA).nes": 781,
  "Rocketeer, The (USA).nes": 782,
  "Rockin' Kats (USA).nes": 783,
  "Rod Land (Europe).nes": 784,
  "Roger Clemens' MVP Baseball (USA).nes": 785,
  "Rollerball (USA).nes": 786,
  "Rollerblade Racer (USA).nes": 787,
  "Rollergames (USA).nes": 788,
  "Rolling Thunder (USA) (Unl).nes": 789,
  "Romance of the Three Kingdoms (USA).nes": 790,
  "Romance of the Three Kingdoms II (USA).nes": 791,
  "Romancia (Japan) (Translated En).nes": 792,
  "Roundball - 2-on-2 Challenge (USA).nes": 793,
  "Route-16 Turbo (Japan).nes": 794,
  "Rush'n Attack (USA).nes": 795,
  "Rygar (USA) (Rev A).nes": 796,
  "S.C.A.T. - Special Cybernetic Attack Team (USA).nes": 797,
  "SD Keiji - Blader (Japan) (Translated En).nes": 798,
  "Saiyuuki World 2 - Tenjoukai no Majin (Japan) (Translated En).nes": 799,
  "Sanrio Carnival 2 (Japan) (Translated En).nes": 800,
  "Sanrio Cup - Pon Pon Volley (Japan) (Translated En).nes": 801,
  "Secret Scout in the Temple of Demise (USA) (Unl).nes": 802,
  "Section-Z (USA).nes": 803,
  "Seicross (USA).nes": 804,
  "Seirei Gari (Japan) (Translated En).nes": 805,
  "Sesame Street - Big Bird's Hide & Speak (USA).nes": 806,
  "Sesame Street 123 (USA).nes": 807,
  "Sesame Street ABC & 123 (USA).nes": 808,
  "Sesame Street ABC (USA).nes": 809,
  "Sesame Street Countdown (USA).nes": 810,
  "Shadow of the Ninja (USA).nes": 811,
  "Shadowgate (USA).nes": 812,
  "Shanghai (Japan).nes": 813,
  "Shanghai II (Japan).nes": 814,
  "Shatterhand (USA).nes": 815,
  "Shikinjou (Japan) (Translated En).nes": 816,
  "Shingen the Ruler (USA).nes": 817,
  "Shinobi (USA) (Unl).nes": 818,
  "Shinsenden (Japan) (Translated En).nes": 819,
  "Shockwave (USA) (Unl).nes": 820,
  "Shooting Range (USA).nes": 821,
  "Short Order + Egg-Splode! (USA).nes": 822,
  "Shufflepuck Cafe (Japan) (Translated En).nes": 823,
  "Side Pocket (USA).nes": 824,
  "Silent Assault (USA) (Unl).nes": 825,
  "Silent Service (USA) (Rev A).nes": 826,
  "Silk Worm (USA).nes": 827,
  "Silva Saga (Japan) (Translated En).nes": 828,
  "Silver Surfer (USA).nes": 829,
  "Simpsons, The - Bart vs. the Space Mutants (USA) (Rev A).nes": 830,
  "Simpsons, The - Bart vs. the World (USA).nes": 831,
  "Simpsons, The - Bartman Meets Radioactive Man (USA).nes": 832,
  "Skate or Die (USA).nes": 833,
  "Skate or Die 2 - The Search for Double Trouble (USA).nes": 834,
  "Ski or Die (USA).nes": 835,
  "Skull & Crossbones (USA) (Unl).nes": 836,
  "Sky Destroyer (Japan).nes": 837,
  "Sky Kid (USA).nes": 838,
  "Sky Shark (USA) (Rev 0A).nes": 839,
  "Slalom (USA).nes": 840,
  "Smash T.V. (USA).nes": 841,
  "Smurfs, The (Europe) (En,Fr,De,Es).nes": 842,
  "Snake Rattle n Roll (USA).nes": 843,
  "Snake's Revenge (USA).nes": 844,
  "Snoopy's Silly Sports Spectacular! (USA).nes": 845,
  "Snow Brothers (USA).nes": 846,
  "Soccer (World).nes": 847,
  "Solar Jetman - Hunt for the Golden Warpship (USA).nes": 848,
  "Solitaire (USA) (Unl).nes": 849,
  "Solomon's Key (USA).nes": 850,
  "Solomon's Key 2 (Europe).nes": 851,
  "Solstice - The Quest for the Staff of Demnos (USA).nes": 852,
  "Son Son (Japan).nes": 853,
  "Space Harrier (Japan).nes": 854,
  "Space Invaders (Japan).nes": 855,
  "Space Shadow (Japan).nes": 856,
  "Space Shuttle Project (USA).nes": 857,
  "Spartan X 2 (Japan) (Translated En).nes": 858,
  "Spelunker (USA).nes": 859,
  "Spelunker II - Yuusha e no Chousen (Japan) (Translated En).nes": 860,
  "Spider-Man - Return of the Sinister Six (USA).nes": 861,
  "Spiritual Warfare (USA) (v6.1) (Unl).nes": 862,
  "Splatter House - Wanpaku Graffiti (Japan).nes": 863,
  "Spot - The Video Game (USA).nes": 864,
  "Spy Hunter (USA).nes": 865,
  "Spy vs Spy (USA).nes": 866,
  "Sqoon (USA).nes": 867,
  "Stack-Up (World).nes": 868,
  "Stadium Events (USA).nes": 869,
  "Stanley - The Search for Dr. Livingston (USA).nes": 870,
  "Star Force (USA).nes": 871,
  "Star Luster (Japan).nes": 872,
  "Star Soldier (USA).nes": 873,
  "Star Trek - 25th Anniversary (USA).nes": 874,
  "Star Trek - The Next Generation (USA).nes": 875,
  "Star Voyager (USA).nes": 876,
  "Star Wars (Japan) (Namco) (Translated En).nes": 877,
  "Star Wars (USA).nes": 878,
  "Star Wars - The Empire Strikes Back (USA).nes": 879,
  "StarTropics (USA).nes": 880,
  "StarTropics II - Zoda's Revenge (USA).nes": 881,
  "Starship Hector (USA).nes": 882,
  "Stealth ATF (USA).nes": 883,
  "Sted - Iseki Wakusei no Yabou (Japan) (Translated En).nes": 884,
  "Stick Hunter - Exciting Ice Hockey (Japan).nes": 885,
  "Stinger (USA).nes": 886,
  "Street Cop (USA).nes": 887,
  "Street Fighter 2010 - The Final Fight (USA).nes": 888,
  "Strider (USA).nes": 889,
  "Stunt Kids (USA) (Unl).nes": 890,
  "Sugoro Quest - Dice no Senshitachi (Japan) (Translated En).nes": 891,
  "Summer Carnival '92 - Recca (Japan).nes": 892,
  "Sunday Funday - The Ride (USA) (Unl).nes": 893,
  "Super Arabian (Japan).nes": 894,
  "Super Black Onyx (Japan).nes": 895,
  "Super C (USA).nes": 896,
  "Super Cars (USA).nes": 897,
  "Super Dodge Ball (USA).nes": 898,
  "Super Dyna'mix Badminton (Japan).nes": 899,
  "Super Glove Ball (USA).nes": 900,
  "Super Jeopardy! (USA).nes": 901,
  "Super Mario Bros. (World).nes": 902,
  "Super Mario Bros. + Duck Hunt (USA).nes": 903,
  "Super Mario Bros. + Duck Hunt + World Class Track Meet (USA) (Rev A).nes": 904,
  "Super Mario Bros. + Tetris + Nintendo World Cup (Europe) (Rev A).nes": 905,
  "Super Mario Bros. 2 (USA) (Rev A).nes": 906,
  "Super Mario Bros. 3 (USA) (Rev A).nes": 907,
  "Super Pinball (Japan).nes": 908,
  "Super Pitfall (USA).nes": 909,
  "Super Spike V'Ball (USA).nes": 910,
  "Super Spike V'Ball + Nintendo World Cup (USA).nes": 911,
  "Super Sprint (USA) (Unl).nes": 912,
  "Super Spy Hunter (USA).nes": 913,
  "Super Team Games (USA).nes": 914,
  "Super Turrican (Europe).nes": 915,
  "Super Xevious - Gump no Nazo (Japan).nes": 916,
  "Superman (USA).nes": 917,
  "Swamp Thing (USA).nes": 918,
  "Sweet Home (Japan) (Translated En).nes": 919,
  "Sword Master (USA).nes": 920,
  "Swords and Serpents (USA).nes": 921,
  "Taboo - The Sixth Sense (USA) (Rev A).nes": 922,
  "Tag Team Wrestling (USA).nes": 923,
  "Tagin' Dragon (USA) (Unl).nes": 924,
  "Taito Chase H.Q. (Japan).nes": 925,
  "Takahashi Meijin no Bouken-jima IV (Japan) (Translated En).nes": 926,
  "Takahashi Meijin no Bugutte Honey (Japan).nes": 927,
  "TaleSpin (USA).nes": 928,
  "Tao (Japan) (Translated En).nes": 929,
  "Target Renegade (USA).nes": 930,
  "Tashiro Masashi no Princess ga Ippai (Japan) (Translated En).nes": 931,
  "Tecmo Baseball (USA).nes": 932,
  "Tecmo Bowl (USA) (Rev A).nes": 933,
  "Tecmo Cup - Soccer Game (USA).nes": 934,
  "Tecmo NBA Basketball (USA) (Rev A).nes": 935,
  "Tecmo Super Bowl (USA).nes": 936,
  "Tecmo World Cup Soccer (Europe).nes": 937,
  "Tecmo World Wrestling (USA).nes": 938,
  "Teenage Mutant Ninja Turtles (USA).nes": 939,
  "Teenage Mutant Ninja Turtles - Tournament Fighters (USA).nes": 940,
  "Teenage Mutant Ninja Turtles II - The Arcade Game (USA).nes": 941,
  "Teenage Mutant Ninja Turtles III - The Manhattan Project (USA).nes": 942,
  "Tenchi o Kurau II - Shokatsu Koumei Den (Japan) (Translated En).nes": 943,
  "Tennis (Japan, USA).nes": 944,
  "Terminator 2 - Judgment Day (USA).nes": 945,
  "Terminator, The (USA, Europe).nes": 946,
  "Terra Cresta (USA).nes": 947,
  "Tetrastar - The Fighter (Japan).nes": 948,
  "Tetris (Bulletproof) (Japan) (Rev B).nes": 949,
  "Tetris (USA).nes": 950,
  "Tetris 2 (USA).nes": 951,
  "Tetris 2 + Bombliss (Japan) (Rev A).nes": 952,
  "Thexder (Japan).nes": 953,
  "Three Stooges, The (USA).nes": 954,
  "Thunder & Lightning (USA).nes": 955,
  "Thunderbirds (USA).nes": 956,
  "Thundercade (USA).nes": 957,
  "Tiger-Heli (USA).nes": 958,
  "Tiles of Fate (USA) (Unl).nes": 959,
  "Time Lord (USA).nes": 960,
  "Time Zone (Japan) (Translated En).nes": 961,
  "Times of Lore (USA).nes": 962,
  "Tiny Toon Adventures (USA).nes": 963,
  "Tiny Toon Adventures 2 - Trouble in Wackyland (USA).nes": 964,
  "Tiny Toon Adventures Cartoon Workshop (USA).nes": 965,
  "Titan (Japan).nes": 966,
  "To the Earth (USA).nes": 967,
  "Toki (USA).nes": 968,
  "Tokkyuu Shirei - Solbrain (Japan) (Translated En).nes": 969,
  "Tom & Jerry - The Ultimate Game of Cat and Mouse! (USA).nes": 970,
  "Tombs & Treasure (USA).nes": 971,
  "Toobin' (USA) (Unl).nes": 972,
  "Top Gun (USA) (Rev A).nes": 973,
  "Top Gun - The Second Mission (USA).nes": 974,
  "Top Rider (Japan).nes": 975,
  "Total Recall (USA).nes": 976,
  "Totally Rad (USA).nes": 977,
  "Touch Down Fever (USA).nes": 978,
  "Toukon Club (Japan) (Translated En).nes": 979,
  "Tower of Druaga, The (Japan).nes": 980,
  "Town & Country Surf Designs - Thrilla's Surfari (USA).nes": 981,
  "Town & Country Surf Designs - Wood & Water Rage (USA).nes": 982,
  "Toxic Crusaders (USA).nes": 983,
  "Track & Field (USA).nes": 984,
  "Track & Field II (USA) (Rev A).nes": 985,
  "Transformers - Convoy no Nazo (Japan).nes": 986,
  "Treasure Master (USA).nes": 987,
  "Triathron, The (Japan).nes": 988,
  "Trog! (USA).nes": 989,
  "Trojan (USA).nes": 990,
  "Trolls in Crazyland, The (Europe).nes": 991,
  "Trolls on Treasure Island (USA) (Unl).nes": 992,
  "Twin Cobra (USA).nes": 993,
  "Twin Eagle (USA).nes": 994,
  "TwinBee (Japan).nes": 995,
  "TwinBee 3 - Poko Poko Daimaou (Japan) (Translated En).nes": 996,
  "Uchuu Keibitai SDF (Japan).nes": 997,
  "Ufouria - The Saga (Europe).nes": 998,
  "Ultima - Exodus (USA).nes": 999,
  "Ultima - Quest of the Avatar (USA).nes": 1000,
  "Ultima - Warriors of Destiny (USA).nes": 1001,
  "Ultimate Air Combat (USA).nes": 1002,
  "Ultimate Basketball (USA).nes": 1003,
  "Ultimate League Soccer (USA) (Unl).nes": 1004,
  "Ultimate Stuntman, The (USA) (Unl).nes": 1005,
  "Uncanny X-Men, The (USA).nes": 1006,
  "Uncharted Waters (USA).nes": 1007,
  "Uninvited (USA).nes": 1008,
  "Untouchables, The (USA) (Rev B).nes": 1009,
  "Urban Champion (World).nes": 1010,
  "Urusei Yatsura - Lum no Wedding Bell (Japan).nes": 1011,
  "Valis - The Fantastic Soldier (Japan) (Translated En).nes": 1012,
  "Valkyrie no Bouken - Toki no Kagi Densetsu (Japan) (Translated En).nes": 1013,
  "Vegas Dream (USA).nes": 1014,
  "Venice Beach Volleyball (USA) (Unl).nes": 1015,
  "Vice - Project Doom (USA).nes": 1016,
  "Videomation (USA).nes": 1017,
  "Vindicators (USA) (Unl).nes": 1018,
  "Volguard II (Japan).nes": 1019,
  "Volleyball (USA, Europe).nes": 1020,
  "WCW World Championship Wrestling (USA).nes": 1021,
  "WWF King of the Ring (USA).nes": 1022,
  "WWF Wrestlemania (USA).nes": 1023,
  "WWF Wrestlemania Challenge (USA).nes": 1024,
  "WWF Wrestlemania Steel Cage Challenge (USA).nes": 1025,
  "Wacky Races (USA).nes": 1026,
  "Wagyan Land (Japan) (Translated En).nes": 1027,
  "Wai Wai World 2 - SOS!! Paseri Jou (Japan) (Translated En).nes": 1028,
  "Wall Street Kid (USA).nes": 1029,
  "Wally Bear and the No! Gang (USA) (Unl).nes": 1030,
  "Wanpaku Kokkun no Gourmet World (Japan) (Translated En).nes": 1031,
  "Wario's Woods (USA).nes": 1032,
  "Warpman (Japan).nes": 1033,
  "Wayne Gretzky Hockey (USA).nes": 1034,
  "Wayne's World (USA).nes": 1035,
  "Werewolf - The Last Warrior (USA).nes": 1036,
  "Wheel of Fortune (USA) (Rev A).nes": 1037,
  "Wheel of Fortune - Family Edition (USA).nes": 1038,
  "Wheel of Fortune - Junior Edition (USA).nes": 1039,
  "Wheel of Fortune Starring Vanna White (USA).nes": 1040,
  "Where in Time Is Carmen Sandiego (USA).nes": 1041,
  "Where's Waldo (USA).nes": 1042,
  "Who Framed Roger Rabbit (USA).nes": 1043,
  "Whomp 'Em (USA).nes": 1044,
  "Widget (USA).nes": 1045,
  "Wild Gunman (World) (Rev A).nes": 1046,
  "Willow (USA).nes": 1047,
  "Wily & Light no Rockboard - That's Paradise (Japan) (Translated En).nes": 1048,
  "Win, Lose or Draw (USA).nes": 1049,
  "Winter Games (USA) (Rev A).nes": 1050,
  "Wit's (Japan).nes": 1051,
  "Wizardry - Knight of Diamonds - The Second Scenario (USA).nes": 1052,
  "Wizardry - Proving Grounds of the Mad Overlord (USA).nes": 1053,
  "Wizards & Warriors (USA) (Rev A).nes": 1054,
  "Wizards & Warriors II - IronSword (USA).nes": 1055,
  "Wizards & Warriors III - Kuros...Visions of Power (USA).nes": 1056,
  "Wolverine (USA).nes": 1057,
  "Woody Poko (Japan) (Translated En).nes": 1058,
  "World Champ - Super Boxing Great Fight (USA).nes": 1059,
  "World Class Track Meet (USA) (Rev A).nes": 1060,
  "World Games (USA).nes": 1061,
  "Wrath of the Black Manta (USA) (Rev A).nes": 1062,
  "Wrecking Crew (World).nes": 1063,
  "Wurm - Journey to the Center of the Earth! (USA).nes": 1064,
  "Xenophobe (USA).nes": 1065,
  "Xevious - The Avenger (USA).nes": 1066,
  "Xexyz (USA).nes": 1067,
  "Yie Ar Kung-Fu (Japan) (Rev 1.4).nes": 1068,
  "Yo! Noid (USA).nes": 1069,
  "Yoshi (USA).nes": 1070,
  "Yoshi's Cookie (USA).nes": 1071,
  "Youkai Club (Japan) (Translated En).nes": 1072,
  "Young Indiana Jones Chronicles, The (USA).nes": 1073,
  "Ys (Japan) (Translated En).nes": 1074,
  "Ys II - Ancient Ys Vanished - The Final Chapter (Japan) (Translated En).nes": 1075,
  "Ys III - Wanderers from Ys (Japan) (Translated En).nes": 1076,
  "Yume Penguin Monogatari (Japan) (Translated En).nes": 1077,
  "Zanac (USA).nes": 1078,
  "Zen - Intergalactic Ninja (USA).nes": 1079,
  "Zippy Race (Japan).nes": 1080,
  "Zombie Hunter (Japan) (Translated En).nes": 1081,
  "Zombie Nation (USA).nes": 1082,
  "Zunou Senkan Galg (Japan).nes": 1083,
};

export default romRegistry;

export function getRomId(filename: string): number | undefined {
  return romRegistry[filename];
}

export function getRomFilename(id: number): string | undefined {
  return Object.keys(romRegistry).find(k => romRegistry[k] === id);
}
